---
title: Listen Up
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  team:
    title: Team
    output: false
  careers:
    title: Careers
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: clients
  values:
    image: 
    is-home-featured: 
    is-artist-and-label-press-featured: 
    is-events-press-featured: 
    is-daytime-radio-featured: 
    is-specialist-radio-and-club-featured: 
    is-streaming-promotion-featured: 
    is-client-featured: 
    website: 
    facebook: 
    twitter: 
    instagram: 
    spotify: 
    soundcloud: 
    youtube: 
    apple: 
- scope:
    path: ''
    type: services
  values:
    service: 
    subtitle: 
    excerpt: 
- scope:
    path: ''
    type: team
  values:
    image: 
    job-title: 
    is-featured: 
    email: 
url: https://www.listen-up.biz
description: Listen Up provides a bespoke 360 promotional service offering radio,
  club, streaming promotion and press campaigns globally
about-text: "Established in 2009 Listen Up offer a tailored range of bespoke radio, club, digital marketing, online and print promotion campaigns globally through our LA and London offices. In 2014 after recognizing a gap in the market we moved our services stateside and opened an additional arm of the business in LA. Specializing in various music genres and events, we place our clients directly in the spotlight with the experience and knowhow to oversee thoughtful, effective and engaging campaigns. With a client roster boasting the likes of MK, Snakehips, Jonas Blue, Gorgon City, Black Coffee, Theophilus London, Snakehips, Marshmello, and Samm Henshaw, Listen Up are now recognized as one of the market leaders in the world of music promotion services. We have grown massively over the last 7 years with offices in the UK, US, and Asia alongside 6 companies working under our Listen Up umbrella."
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Listen Up Online Promotions Ltd
email: hello@listen-up.biz
google_site_verification: Kx8OEQISNl9almmvWKiQXaeKUy4594ZKTdBHw3mYoy8
analytics: UA-91478170-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/listenupbiz
  instagram: https://www.instagram.com/listenupbiz/
  twitter: https://twitter.com/ListenUpbiz
  linkedin: https://www.linkedin.com/company/listen-up-music-pr
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
imgix:
  source: listen-up.imgix.net